name: saweha
description: "Saweha: Digital Ledger for Group Expense Management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # حزم الترجمة الأساسية
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.2
  google_fonts: ^8.2.0
  flutter_riverpod: ^3.3.2
  firebase_core: ^4.12.1
  flutter_native_splash: ^2.4.8
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # هذا السطر هو الأهم، ويجب أن يكون تحته بمسافتين فقط
  generate: true

  assets:
    - assets/images/profile.jpg

flutter_native_splash:
  # لون الخلفية العاجي الخاص بتطبيق سويها
  color: "#F6F7EF"
  # مسار صورة الشعار (يفضل أن تكون صورة بخلفية شفافة وبحجم مناسب)
  image: assets/images/logo_light.png
  # تفعيل الشاشة للأندرويد والـ iOS
  android: true
  ios: true

  # إعدادات الوضع الداكن (اختياري، إذا كنت ستدعم الـ Dark Mode)
  color_dark: "#1F1C10" # لون الخلفية في الوضع الداكن
  image_dark: assets/images/logo_dark.png